### ISSUE TITLE
Generating LANGUAGE_MAP

### ISSUE THREAD

**Issue by Slowika** [ElementAI/synbols#24]
Hi, thanks for releasing the dataset. 

Can you please clarify how to generate LANGUAGE_MAP without running `synbols-jupyter`? 

It works well in the jupyter notebook but when I run a python script with the same code LANGUAGE_MAP is empty.

**Comment by aldro61** [comment]
Hi @Slowika,

The LANGUAGE_MAP will only be non-empty when running inside the Synbols runtime environment, i.e., inside the Docker image that ships with each release. If you want to run a custom Python script that uses synbols, you should use `synbols myscript.py` instead of `python myscript.py` to run it (see here https://github.com/ElementAI/synbols#defining-your-own-generator).

Alex

**Comment by aldro61** [comment]
@Slowika did this resolve your issue? Let me know if it didn't.

**Comment by aldro61** [comment]
I'm closing this for now. Please reopen if you are still having issues.
