### ISSUE TITLE
window OS doesn't work with getuid

### ISSUE THREAD

**Issue by Ann-shell** [ElementAI/synbols#29]
C:\Users\XiaoJ>synbols-datasets
Synbols (1.0.0) found at c:\users\xiaoj\anaconda3\lib\site-packages\synbols
Traceback (most recent call last):
  File "c:\users\xiaoj\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\xiaoj\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\XiaoJ\Anaconda3\Scripts\synbols.exe\__main__.py", line 7, in <module>
  File "c:\users\xiaoj\anaconda3\lib\site-packages\synbols\entrypoints\run_docker.py", line 165, in main
    ports=args.docker_port, args=script_args)
  File "c:\users\xiaoj\anaconda3\lib\site-packages\synbols\entrypoints\run_docker.py", line 84, in run_in_docker
    arg_list = f"docker run --rm --user {os.getuid()} -it".split()
AttributeError: module 'os' has no attribute 'getuid'

**Comment by aldro61** [comment]
Hi @Ann-shell!

Thanks for reporting this. Until now, we have only tested Synbols on MacOS and Linux, but there is no reason why it couldn't work on Windows too. 

I was able to reproduce your issue in a CircleCI Windows environment. I'll work on a fix and update you with progress.

![image](https://user-images.githubusercontent.com/2374980/99586981-704fd980-29b6-11eb-9e81-a6b60b894547.png)

**Comment by aldro61** [comment]
In the meantime, I would recommend that you simply setup synbols in a Linux virtual machine (e.g., using Ubuntu with [Virtual box](https://www.virtualbox.org/)). This may be the easiest way to go.

The main issue for running Synbols on Windows is that we rely on mounting paths from your system into the Docker container. This means that:

1. The paths must match on your system vs the Docker container (non-trivial on Windows due to Unix vs Windows-style paths)
2. We need to make sure that the user inside the Docker container has sufficient permissions to write to your system directories (hence the `--user {os.getuid(0)}` part) in the command that fails on Windows).

So if you're looking for a quick resolution, I'd definitely go for the virtual machine solution.

**Comment by aldro61** [comment]
Hello again,

We've decided not to support Windows for now due to the extra complications mentioned above and the complexity of maintaining a Windows development environment for the team. If there is enough demand, we will reopen the issue and look into this more seriously.

In the meantime, please use the virtual machine solution mentioned above to run the Synbols generator from a Windows host.

Cheers,
Alex

**Comment by Ann-shell** [comment]
> Hello again,
> 
> We've decided not to support Windows for now due to the extra complications mentioned above and the complexity of maintaining a Windows development environment for the team. If there is enough demand, we will reopen the issue and look into this more seriously.
> 
> In the meantime, please use the virtual machine solution mentioned above to run the Synbols generator from a Windows host.
> 
> Cheers,
> Alex

Hi Alex,

Thank you so much! We would try to use a virtual box, or do you think we could process the docker on Mac?

Best,
Jingyi

**Comment by aldro61** [comment]
Mac or Linux with Docker installed will definitely work.
